const {chromium}=require('/opt/codex/cua_node/lib/node_modules/playwright');
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
(async()=>{const root=path.resolve(__dirname,'dist'),server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1050}});page.setDefaultTimeout(60000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.duelTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.duelTools[t.name]=t;}}});});await page.clock.install();await page.goto('http://127.0.0.1:'+server.address().port);const state=()=>page.evaluate(()=>window.duelTools.read_duel_state.execute({}));await page.locator('#cancel-loadout').click();assert.equal(await page.locator('[data-class]').count(),6);
await page.locator('[data-class="flame"]').click();assert.equal(await page.locator('[data-major]').count(),2);assert.equal(await page.locator('[data-equip]').count(),8);assert.equal(await page.locator('[data-equip][aria-pressed="true"]').count(),6);assert.ok((await page.locator('#loadout-passive').textContent()).includes('基础火伤'));await page.locator('[data-major="smolder"]').click();await page.locator('#apply-loadout').click();assert.equal((await state()).player.key,'flame');assert.equal((await state()).player.major,'smolder');assert.ok(await page.locator('[data-skill="combust"]').isDisabled());assert.ok((await page.locator('[data-skill="combust"]').textContent()).includes('目标需要'));await page.locator('[data-skill="kindle"]').click();assert.equal((await state()).enemy.burn,3);await page.locator('[data-skill="cinder"]').click();assert.equal((await state()).enemy.burn,1);assert.equal((await state()).enemy.burnTurns,2);assert.ok((await page.locator('#battle-log').textContent()).includes('剩余 1 层'));
for(const major of ['fierce','smolder']){
 await page.locator('#trial-button').click();await page.locator('[data-difficulty="questioning"]').click();await page.locator('[data-practice="fierce"]').click();await page.locator('[data-loadout-class="flame"]').click();await page.locator(`[data-major="${major}"]`).click();await page.locator('#apply-loadout').click();const ready=await state();assert.equal(ready.player.key,'flame');assert.equal(ready.enemy.key,'flame');assert.equal(ready.opponentId,'fierce');assert.equal(ready.difficulty,'questioning');assert.ok((await page.locator('#opponent-brief').textContent()).includes('火气'));
 await page.locator('#auto-speed').selectOption('fast');await page.locator('#auto-tendency').selectOption(major==='fierce'?'aggressive':'balanced');await page.locator('#auto-toggle').click();await page.clock.runFor(90000);const done=await state();assert.ok(done.result);assert.equal(done.automation.enabled,false);assert.equal(await page.locator('#battle-log .log-entry').count(),done.logCount);await page.locator('#history-button').click();assert.ok((await page.locator('#history-review').textContent()).includes('灼烧兑现（层）'));assert.ok((await page.locator('#history-log').textContent()).includes('祝燃灯'));await page.locator('#close-history').click();
}
for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.locator('[data-class="flame"]').click();await page.locator('[data-major="smolder"]').click();assert.ok(await page.evaluate(()=>document.querySelector('#loadout-dialog').scrollWidth<=document.querySelector('#loadout-dialog').clientWidth+1));await page.locator('#apply-loadout').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const hud=await page.locator('.arena-hud').boundingBox(),art=await page.locator('#player-art').boundingBox();assert.ok(hud.y+hud.height<=art.y);await page.screenshot({path:`/workspace/qingxiao-flame-${width}.png`,fullPage:true});}
assert.ok(await page.evaluate(()=>[...document.images].every(im=>im.complete&&im.naturalWidth>0)));assert.deepEqual(errors,[]);console.log('Browser pure fire: four paths, two majors, eight-select-six, burn prerequisites/cashout, same-class questioning NPC, automatic combat, full history/review and 1440/390/320 layouts with clear portraits passed.');}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1);});
