import assert from 'node:assert/strict';
import {Battle,CLASSES,MAJORS,total} from './dist/engine.mjs';
import {DuelBattle} from './dist/duel-setup.mjs';
import {TACTICAL_SKILLS,TACTICAL_LOADOUTS} from './dist/tactics.mjs';
import {startPreparedPhase} from './dist/prepared.mjs';
import {normalizeRecord} from './dist/save.mjs';
import {Trial} from './dist/trial.mjs';
import {chooseReaction} from './dist/auto.mjs';
const equip=(key,id)=>[id,...CLASSES[key].skills.map(s=>s.id).filter(x=>x!==id)].slice(0,6);
function board(key,id,enemy='sword'){const b=new DuelBattle(key,{skillIds:equip(key,id)},{key:enemy});b.player.qi={metal:0,water:0,fire:0,wood:0,earth:0,any:1,[key==='sword'?'metal':key==='fire'?'wood':key==='flame'?'fire':key]:5};if(key==='sword')b.player.qi.water=2;if(key==='fire')b.player.qi.fire=3;b.player.ap=3;b.player.hp=100;b.player.intent=3;b.player.growth=2;b.player.terrain=2;b.player.tide=2;b.enemy.seed=3;b.enemy.parasite=2;b.enemy.chilled=true;b.enemy.burn=3;b.enemy.burnTurns=2;b.enemy.reaction=false;return b;}
let count=0;
for(const [key,skills] of Object.entries(TACTICAL_SKILLS)){
 assert.equal(CLASSES[key].skills.length,12);
 for(const s of skills){const b=board(key,s.id);if(s.kind==='channel'){b.player.qi.wood=2;b.player.qi.fire=1;}const before=structuredClone(b.player),enemy=structuredClone(b.enemy);assert.equal(b.legal(b.player,s.id),null,s.id);assert.ok(b.act(b.player,s.id).ok,s.id);assert.equal(b.player.ap,3-s.ap,s.id);assert.ok(total(b.player.qi)<=10);assert.ok(Object.values(b.player.qi).every(n=>n>=0));if(s.consumeSeed)assert.equal(b.enemy.seed,enemy.seed-Math.min(enemy.seed,s.consumeSeed));if(s.consumeGrowth)assert.equal(b.player.growth,before.growth-Math.min(before.growth,s.consumeGrowth));if(s.consumeTerrain)assert.equal(b.player.terrain,before.terrain-Math.min(before.terrain,s.consumeTerrain));if(s.consumeTide)assert.equal(b.player.tide,before.tide-Math.min(before.tide,s.consumeTide));if(s.consumeParasite)assert.equal(b.enemy.parasite,enemy.parasite-Math.min(enemy.parasite,s.consumeParasite));if(s.consumeChill)assert.equal(b.enemy.chilled,false);if(s.once&&b.player.ap>=s.ap)assert.ok(b.legal(b.player,s.id));count++;}
 for(const major of Object.keys(MAJORS[key]))assert.equal(new Battle(key,{major,skillIds:TACTICAL_LOADOUTS[key][major]}).player.skillIds.length,6);
}
assert.equal(count,24);
const pierce=board('sword','pierce');pierce.enemy.shield=60;const damage=pierce.preview(pierce.skill(pierce.player,'pierce'));const hp=pierce.enemy.hp;assert.ok(pierce.act(pierce.player,'pierce').ok);assert.equal(hp-pierce.enemy.hp,damage-Math.floor(damage*.5));assert.ok(pierce.enemy.shield>0,'Pierce spends extra resources without deleting the shield');
const danger=new Battle('sword');danger.player.hp=10;danger.player.shield=60;danger.player.qi={metal:0,water:2,wood:0,fire:0,earth:0,any:0};danger.phase='reaction';danger.pending={s:{id:'pierce',kind:'attack',element:'metal',damageType:'physical',shieldPierce:.5},raw:32};assert.equal(chooseReaction(danger).response,'evade','AI sees lethal shield bypass and chooses a surviving response');
const grown=board('wood','graft');grown.player.growth=0;grown.player.growthPending=false;grown.act(grown.player,'graft');assert.equal(grown.player.growth,2);assert.equal(grown.player.growthPending,false);startPreparedPhase(grown,grown.player);assert.equal(grown.player.growth,2,'Instant growth does not mature a second time');
const seeded=board('fire','rootdrink');seeded.act(seeded.player,'rootdrink');assert.equal(seeded.player.hp,126);assert.equal(seeded.enemy.seed,1);assert.equal(seeded.stats[0].healing,26);assert.equal(seeded.stats[0].overheal,0);
const tidal=board('water','mendingtide');tidal.act(tidal.player,'mendingtide');assert.equal(tidal.player.hp,124);assert.equal(tidal.player.tide,0);assert.equal(tidal.stats[0].tideSpent,2);
const blood=board('flame','stoke');blood.player.hp=18;const exact=structuredClone(blood.snapshot());assert.equal(blood.act(blood.player,'stoke').ok,false);assert.deepEqual(blood.snapshot(),exact);blood.player.hp=19;blood.player.qi.fire=0;blood.player.qi.any=0;assert.ok(blood.act(blood.player,'stoke').ok);assert.equal(blood.player.hp,1);assert.equal(total(blood.player.qi),3);
const reflect=board('wood','thornscreen','flame');reflect.enemy.shield=0;reflect.act(reflect.player,'thornscreen');const power=reflect.player.counter.power;assert.equal(power,16);assert.equal(reflect.player.counter.hits,2);reflect.enemy.counter={name:'测试对手反伤',element:'fire',power:30,hits:2};reflect.enemy.qi.fire=6;reflect.enemy.ap=3;reflect.phase='enemy';const ehp=reflect.enemy.hp;assert.ok(reflect.act(reflect.enemy,'flare').ok);if(reflect.phase==='reaction')reflect.react('none');assert.ok(reflect.enemy.hp<ehp);assert.equal(reflect.enemy.counter.hits,2,'Reflected damage cannot reflect recursively');assert.equal(reflect.player.counter.hits,1);assert.ok(reflect.stats[0].reflectionDamage>0);
reflect.player.burn=2;reflect.player.burnTurns=2;reflect.tickBurn(reflect.player);assert.equal(reflect.player.counter.hits,1,'Burn does not consume the retaliation');reflect.tickParasite(reflect.enemy,8);assert.equal(reflect.player.counter.hits,1,'Parasite does not consume it');startPreparedPhase(reflect,reflect.player);assert.equal(reflect.player.counter,null);
const archive=new Trial();const record=archive.archive(reflect,{abandoned:true});assert.ok(normalizeRecord(record).review.events.some(e=>e.type==='reflection'),'Reflections survive save normalization');
console.log('24 new skills: resource/AP bounds, shared consumption, immediate growth, healing stats, shield piercing, nonlethal sacrifice, limited nonrecursive reflection and old/new record compatibility passed.');
