import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {gzipSync,gunzipSync} from 'node:zlib';
import {sequenceVariants,patchNourish} from './sequence-variants.mjs';
import {build,pairs,monitoredDuel,aggregate} from './sequence-review.mjs';
const step=Number(process.argv[2]),dir=`docs/balance/sequence-${step}`;assert.ok([5,6,7].includes(step));mkdirSync(dir,{recursive:true});const rows=[],started=performance.now();let executions=0,retainedElapsed=0;
const specs=step===5?[{id:'base'},{id:'heal10',patch:patchNourish('heal',10)},{id:'clear0',patch:patchNourish('clearBurn',0)},{id:'refund0',patch:patchNourish('refund',0)},{id:'ap2',patch:patchNourish('ap',2)}]:[{id:'base'}];const v=await sequenceVariants(specs);
const save=()=>writeFileSync(dir+'/results.json.gz',gzipSync(JSON.stringify({step,rows}),{level:9}));
const run=(c,a,b,opts={},extra={})=>{let t=performance.now();const result=monitoredDuel(c,a,b,opts);rows.push({variant:c.id,a,b,first:opts.first??0,distance:opts.distance??1,controller:opts.controller??'adaptive',compensation:opts.compensation??null,...extra,...result,ms:performance.now()-t});executions++;save();if(executions%8===0)console.log(`step${step} ${executions} executions ${(performance.now()-started)/1000|0}s`);};
try{
 if(step===5&&!process.argv.includes('--cleanse-mirrors')){const recommended=v.list[0].engine.MAJORS.fire;for(const c of v.list)for(const controller of ['immediate','script'])for(const major of ['ignite','sustain'])for(const enemy of ['quick','heavy'])for(const distance of [1,2])for(const first of [0,1]){const skills=[...recommended[major].recommended];if(!skills.includes('nourish'))skills[skills.indexOf('vine')]='nourish';run(c,build(major,skills),build(enemy),{controller,distance,first},{group:'equipped-screen'});}
 // Resource refund merits a separate adaptive confirmation, irrespective of directional win change.
 for(const c of v.list.filter(c=>['base','refund0'].includes(c.id)))for(const enemy of ['quick','heavy'])for(const distance of [1,2])for(const first of [0,1])run(c,build('sustain'),build(enemy),{distance,first},{group:'refund-confirmation'});
 // A skill not equipped must make its isolated mutation a true negative control.
 for(const controller of ['immediate','script'])for(const enemy of ['quick','heavy'])for(const first of [0,1]){const start=rows.length;for(const c of v.list.filter(c=>['base','refund0'].includes(c.id)))run(c,build('ignite'),build(enemy),{controller,first},{group:'not-equipped-control'});for(const key of ['winner','rounds','hp','metrics','trace'])assert.deepEqual(rows[start][key],rows[start+1][key],'Unequipped skill mutation changed combat');}
 // Controlled damaged/burning states: literal effects including passive and opportunity cost.
 const tactics=[];for(const c of v.list)for(const major of ['ignite','sustain'])for(const burn of [0,1,5]){const w=c.runtime.createPredictiveArena(build(major),build('quick'),{controllers:['immediate','immediate']});if(!w.actors[0].skillIds.includes('nourish'))w.actors[0].skillIds[4]='nourish';const a=w.actors[0];a.hp=100;a.burn=burn;a.burnTurns=3;a.qi={metal:0,wood:3,water:0,fire:0,earth:0,any:2};const before=c.runtime.worldState(w);assert.ok(c.runtime.actWorld(w,'nourish').ok);tactics.push({variant:c.id,major,burn,before,after:c.runtime.worldState(w),choiceAfter:c.runtime.chooseArenaAction(w,{controller:'immediate'})});}writeFileSync(dir+'/tactics.json.gz',gzipSync(JSON.stringify(tactics),{level:9}));
 }
 if(step===5){if(process.argv.includes('--cleanse-mirrors')){retainedElapsed=JSON.parse(readFileSync(dir+'/summary.json')).elapsedSeconds;const existing=JSON.parse(gunzipSync(readFileSync(dir+'/results.json.gz')));assert.ok(!existing.rows.some(r=>r.group==='cleanse-mirrors'),'Already appended');rows.push(...existing.rows);}for(const c of v.list.filter(c=>['base','clear0','heal10'].includes(c.id)))for(const controller of ['immediate','script'])for(const major of ['ignite','sustain'])for(const distance of [1,2])for(const first of [0,1]){let skills=[...c.engine.MAJORS.fire[major].recommended];if(!skills.includes('nourish'))skills[skills.indexOf('vine')]='nourish';run(c,build(major,skills),build(major,skills),{controller,distance,first},{group:'cleanse-mirrors'});}}
 if(step===6){const c=v.list[0];for(const compensation of [null,'shield8','qi1'])for(const controller of ['immediate','script'])for(const [a,b] of pairs)for(const distance of [0,1,2])for(const first of [0,1])run(c,build(a),build(b),{compensation,controller,distance,first});for(const compensation of [null,'shield8','qi1'])for(const major of ['ignite','sustain','quick','heavy'])for(const first of [0,1])run(c,build(major),build(major),{compensation,controller:'immediate',first},{group:'mirrors'});for(const compensation of [null,'shield8','qi1'])for(const [a,b] of pairs)for(const first of [0,1])run(c,build(a),build(b),{compensation,first},{group:'adaptive-confirmation'});}
 if(step===7&&!process.argv.includes('--tactics-only')){const c=v.list[0];for(const major of ['ignite','sustain','quick','heavy']){const key=build(major).key,ids=c.engine.CLASSES[key].skills.map(s=>s.id),enemy=key==='fire'?'heavy':'sustain';for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)for(const first of [0,1])run(c,build(major,ids.filter((_,k)=>k!==i&&k!==j)),build(enemy),{controller:'immediate',first},{group:'all28',omitted:[ids[i],ids[j]]});
 const groups=rows.filter(r=>r.a.config.major===major&&r.group==='all28');const sets=[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const matches=groups.filter(r=>r.omitted[0]===ids[i]&&r.omitted[1]===ids[j]);sets.push({ids:matches[0].a.config.skillIds,omitted:matches[0].omitted,score:matches.reduce((s,r)=>s+(r.winner===0?1000:r.winner===null?0:-1000)+r.hp[0]-r.hp[1],0)});}sets.sort((a,b)=>b.score-a.score);const candidates=[{ids:c.engine.MAJORS[key][major].recommended,label:'recommended'},{ids:sets[0].ids,label:'screen-best'},{ids:sets.at(-1).ids,label:'screen-worst'}];for(const candidate of candidates)for(const controller of ['script','adaptive'])for(const first of [0,1])run(c,build(major,candidate.ids),build(enemy),{controller,first},{group:'confirmation',selection:candidate.label});}
 }
 if(step===7&&process.argv.includes('--tactics-only')){retainedElapsed=JSON.parse(readFileSync(dir+'/summary.json')).elapsedSeconds;rows.push(...JSON.parse(gunzipSync(readFileSync(dir+'/results.json.gz'))).rows);}
 if(step===7){const c=v.list[0],tactics=[];for(const [major,id,distance] of [['ignite','vine',1],['ignite','ember',2],['quick','cut',1],['quick','lunge',0],['heavy','return',1]]){const key=build(major).key,skills=[...c.engine.MAJORS[key][major].recommended];if(!skills.includes(id))skills[0]=id;const w=c.runtime.createPredictiveArena(build(major,skills),build(key==='fire'?'heavy':'ignite'),{distance});const a=w.actors[0],b=w.actors[1];a.intent=key==='sword'?5:0;a.qi=Object.fromEntries(c.engine.ELEMENTS.map(k=>[k,0]));Object.assign(a.qi,key==='fire'?{wood:3,fire:3,any:3}:{metal:4,water:2,any:3});b.seed=key==='fire'?3:0;b.broken=key==='sword';const charge=c.engine.CLASSES[b.key].skills.find(s=>s.kind==='charge');b.charge={...charge,storedPower:86};const before=c.runtime.worldState(w),included=c.planner.options(w.battle,'balanced').some(s=>s.id===id);assert.ok(c.runtime.actWorld(w,id).ok);const after=c.runtime.worldState(w);if(['vine','cut','lunge'].includes(id))assert.equal(b.charge,null);if(id==='ember')assert.equal(b.seed,1);if(id==='return')assert.equal(a.intent,3);tactics.push({major,id,included,distance,before,after});}writeFileSync(dir+'/tactics.json.gz',gzipSync(JSON.stringify(tactics),{level:9}));}
 const summary={step,executions:rows.length,additionalExecutions:executions,retainedRows:rows.length,elapsedSeconds:retainedElapsed+(performance.now()-started)/1000,limit:30,variants:v.list.map(c=>({id:c.id,engineHash:c.engineHash,autoHash:c.autoHash,runtimeHash:c.runtimeHash})),groups:[...new Set(rows.map(r=>JSON.stringify([r.variant,r.controller,r.compensation,r.group??'cross'])))].map(key=>({key,...aggregate(rows.filter(r=>JSON.stringify([r.variant,r.controller,r.compensation,r.group??'cross'])===key))}))};writeFileSync(dir+'/summary.json',JSON.stringify(summary,null,2)+'\n');writeFileSync(dir+'/source.json.gz',gzipSync(JSON.stringify({runner:readFileSync('scripts/sequence-numbers.mjs','utf8'),monitor:readFileSync('scripts/sequence-review.mjs','utf8'),helper:readFileSync('scripts/sequence-variants.mjs','utf8'),variants:v.list.map(c=>({id:c.id,sources:c.sources}))}),{level:9}));console.log(JSON.stringify({done:step,executions,seconds:summary.elapsedSeconds}));
}finally{v.cleanup();}
