import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {aggregate} from './sequence-review.mjs';
const path='docs/七项战斗复查与调整决定.md';let text=readFileSync(path,'utf8');const decode=p=>JSON.parse(gunzipSync(readFileSync(p))),name={ignite:'引燃',sustain:'生息',quick:'快剑',heavy:'重剑'};
function section(n,title,content){const re=new RegExp(`## ${n}\\. [^\\n]+\\n[\\s\\S]*?(?=\\n## |$)`);text=text.replace(re,`## ${n}. ${title}\n\n${content}\n`);}
const table=(headers,rows)=>'| '+headers.join(' | ')+' |\n| '+headers.map(()=>'---').join(' | ')+' |\n'+rows.map(r=>'| '+r.join(' | ')+' |').join('\n');
for(const step of [3,4,5,6,7]){const dir=`docs/balance/sequence-${step}`;if(!existsSync(dir+'/summary.json'))continue;const s=JSON.parse(readFileSync(dir+'/summary.json')),rows=decode(dir+'/results.json.gz').rows;let body=`已完成。新执行 **${s.executions} 场**${s.cachedRows?`，另复用第 3 项 ${s.cachedRows} 场`:''}，每场最多 30 回合；全部原始事件和纪要保留。\n\n`;
 if(step===3){body+='推荐六槽配置：四种跨派组合 × 三距离 × 交换先手 24 场，四主修镜像 × 交换先手 8 场，中距跨派另测稳守／蓄势倾向 × 交换先手 16 场，共 48 场。强攻倾向已有上一轮护盾评分对照，本轮没有重跑完整倾向矩阵。\n\n';body+=table(['组合（甲／乙）','场数','甲胜／乙胜／未决','先行动者胜','平均回合','闲置 AP'],[...new Set(rows.map(r=>r.a.config.major+'/'+r.b.config.major))].map(key=>{const rs=rows.filter(r=>r.a.config.major+'/'+r.b.config.major===key),a=aggregate(rs);return [key.split('/').map(k=>name[k]).join('／'),a.n,`${a.wins}/${a.losses}/${a.unresolved}`,a.firstWins,a.meanRounds.toFixed(1),a.unusedAP];}));body+='\n\n';body+=table(['初始距离（均衡跨派）','场数','火木胜／剑修胜／未决','先行动者胜'],[0,1,2].map(d=>{const a=aggregate(rows.filter(r=>r.distance===d&&r.prefs[0]==='balanced'&&r.a.key!==r.b.key));return [['近','中','远'][d],a.n,`${a.wins}/${a.losses}/${a.unresolved}`,a.firstWins];}));body+='\n\n';body+=table(['主修（含双方席位）','蓄势开始／释放／打断／距离落空／未释放','蓄势气血伤害／盾伤','消耗剑意','调息次数'],['ignite','sustain','quick','heavy'].map(major=>{const seats=rows.flatMap(r=>[0,1].filter(i=>(i===0?r.a:r.b).config.major===major).map(i=>({d:r.detail[i],m:r.metrics[i]})));const sum=k=>seats.reduce((n,x)=>n+x.d.charge[k],0);return [name[major],['started','released','interrupted','rangeMiss','pending'].map(sum).join('/'),`${sum('damage')}/${sum('shieldDamage')}`,seats.reduce((n,x)=>n+x.d.intentSpent,0),seats.reduce((n,x)=>n+(x.m.actions.meditate||0),0)];}));body+='\n\n蓄势「未释放」包括到上限以及战斗已结束时仍持有的蓄势；不能算成功释放。释放伤害包括反应减伤与盾吸收后的实际结算。表中的剑意消耗含追击与重剑；不把养剑当作已经兑现的伤害。\n\n**决定：保留现有蓄势费用与伤害，先观察机会成本和应对窗口；不通过提高面板大招伤害来掩盖被打断问题。** 先手、距离和倾向分组继续作为后续必查条件。';}
 if(step===4){body+=table(['控制器','场数','跨派火木胜／剑修胜／未决','跨派先行动者胜','镜像先行动者胜／未决','闲置 AP'],['adaptive','immediate','script'].map(c=>{const rs=rows.filter(r=>r.controller===c),a=aggregate(rs.filter(r=>r.a.key!==r.b.key)),m=aggregate(rs.filter(r=>r.a.key===r.b.key));return [c,rs.length,`${a.wins}/${a.losses}/${a.unresolved}`,a.firstWins,`${m.firstWins}/${m.unresolved}`,aggregate(rs).unusedAP];}));body+='\n\n**采用控制器组合，不采用单一裁判：**\n\n- `adaptive`：原有限层、十二候选、敌盾净变化评分 ×2，作为主要行为复查；可能有边界误判和候选遗漏，不能认定最优策略。\n- `immediate`：看本阶段收益，作为低预测成本的筛选与消融控制；天然低估未来蓄势与持续收益。\n- `script`：双方共享对等规则、用固定公开脚本预测对手，作为脚本敏感性控制；实际双方会重新决策，预测也会失配。\n- 线上 `legacy`：仍服务真实网页的公开预告玩法，其对等离线胜率保留在历史四控制器报告；本轮未重跑。真人复查尚未进行。\n\n数值候选先用 immediate／script 单因素配对，再用 adaptive 确认重点。控制器间矛盾时保留原值、记录分歧，不能选择最符合预期的一个结果。第 1、2 项新模型只作为诊断，不进入本轮数值裁判。';}
 if(step===5){body+='仅修改枯荣一个字段：回血 14→10、清灼烧 1→0、返通灵 1→0、行动 1→2，另有原值对照。主修奖励、木法回火、其他技能与评分不变。引燃测试配置把缠灵藤替换为枯荣；生息沿用推荐配置。\n\n';body+=table(['候选','即时：火木胜／剑修胜／未决','脚本：火木胜／剑修胜／未决','实际枯荣次数（筛选合计）'],['base','heal10','clear0','refund0','ap2'].map(v=>{const rs=rows.filter(r=>r.variant===v&&r.group==='equipped-screen');return [v,...['immediate','script'].map(c=>{const a=aggregate(rs.filter(r=>r.controller===c));return `${a.wins}/${a.losses}/${a.unresolved}`;}),rs.reduce((n,r)=>n+(r.metrics[0].actions.nourish||0),0)];}));body+='\n\n';body+=table(['返气确认（adaptive，生息）','场数','火木胜／剑修胜／未决','枯荣次数'],['base','refund0'].map(v=>{const rs=rows.filter(r=>r.variant===v&&r.group==='refund-confirmation'),a=aggregate(rs);return [v,a.n,`${a.wins}/${a.losses}/${a.unresolved}`,rs.reduce((n,r)=>n+(r.metrics[0].actions.nourish||0),0)];}));body+='\n\n另有 16 场「未装备枯荣」负对照，原值／无返气的结果、伤害、行动、应对与完整纪要逐项一致；30 个固定残血／灼烧片段确认字面效果，不计作完整对局。\n\n枯荣的返气发生在支付后，仍要求支付木 1＋任意 1；正常净耗木 1，占 1 AP、每回合一次。首次木法可回火；生息另回血 2，但不会每次重复触发。把回血、清除、返气、主修奖励拆开，才能看到改动来源。\n\n**决定：本轮保留枯荣 14 回血、清 1、返 1、1 AP。** 单字段对照测到了规则改动与 AI 重新选招合起来的结果，不能直接等同于技能在真人手里的强度，更不因为它兼具数种功能便整体削弱；尤其费用改为 2 AP 会同时削弱本回合攻击机会。当前资料没有提供跨控制器、跨配置一致的采用理由。';}
 if(step===5){body+='\n\n另测 48 场双方装备枯荣的火木镜像（原值／回血10／清除0），覆盖两主修、中远距、交换先手、即时／脚本控制。以下单独看灼烧与长局，不能用无灼烧的剑修对局评价清除效果。\n\n';body+=table(['镜像候选／控制器','场数','先行动者胜／后行动者胜／未决','平均回合','枯荣次数'],s.groups.filter(g=>JSON.parse(g.key)[3]==='cleanse-mirrors').map(g=>{const [v,c]=JSON.parse(g.key);return [v+'／'+c,g.n,`${g.firstWins}/${g.n-g.firstWins-g.unresolved}/${g.unresolved}`,g.meanRounds.toFixed(1),g.actions.nourish||0];}));body+='\n\n脚本预测镜像中，取消枯荣清除使先行动者胜场 4/8→8/8；即时控制的胜负不变。清除并非没有效果，但目前证据不支持取消它；并且这些镜像均结束，没有测得无成本无限恢复。即时筛选中回血10、返气0与2 AP都使枯荣施展次数26→0，火木胜场2→6，脚本控制却略降；这属于出招变化的可观测反例，不能把削弱后胜率上涨解释为技能原本太强。';}
 if(step===6){body+='补偿只在开局给后行动者一次，比较无补偿／护盾 8／通灵 1；不改气血、每回合恢复或行动点。三距离跨派用 immediate／script 各交换先手，另测四主修中距镜像（immediate）及四跨派组合中距 adaptive。\n\n';body+=table(['控制器／组别','补偿','场数','先行动者胜／后行动者胜／未决','平均回合'],s.groups.map(g=>{const [v,c,comp,group]=JSON.parse(g.key);return [c+'／'+group,comp??'无',g.n,`${g.firstWins}/${g.n-g.firstWins-g.unresolved}/${g.unresolved}`,g.meanRounds.toFixed(1)];}));body+='\n\n开局后手补偿不能等同于「后手劣势有多大」：同一配置需交换先手，镜像与跨派分开看，初始距离也是条件。若补偿把部分组合从先手必胜改为后手必胜，也不是自动改善。\n\n**决定：暂不加入统一后手补偿。** 按主修、距离和控制器保留配对数据，不用总体先手胜场直接推出所有对局应额外给灵气或护盾。现有反应和距离博弈继续保留。';}
 if(step===7){body+='四主修分别枚举全部八选六的 28 配装，每配装中距交换先手、即时控制：224 场。火木对推荐重剑，剑修对推荐生息。每主修再取推荐／该筛选最优／该筛选最弱，用 script 与 adaptive 各交换先手确认，共 48 场。最优和最弱只指这次特定筛选；没有穷举双方同时换装、三距离或四倾向。\n\n';body+=table(['主修','即时 56 场：己方胜／败／未决','最优配装（筛选）','最弱配装（筛选）'],['ignite','sustain','quick','heavy'].map(m=>{const rs=rows.filter(r=>r.a.config.major===m&&r.group==='all28'),a=aggregate(rs),sets=[...new Set(rs.map(r=>r.a.config.skillIds.join(',')))].map(ids=>({ids,score:rs.filter(r=>r.a.config.skillIds.join(',')===ids).reduce((n,r)=>n+(r.winner===0?1000:r.winner===null?0:-1000)+r.hp[0]-r.hp[1],0)})).sort((a,b)=>b.score-a.score);return [name[m],`${a.wins}/${a.losses}/${a.unresolved}`,sets[0].ids,sets.at(-1).ids];}));body+='\n\n';body+=table(['主修','技能','携带时胜场／场数','未携带时胜场／场数','实际施展次数','合法决策点／被 AI 过滤点'],['ignite','sustain','quick','heavy'].flatMap(m=>{const rs=rows.filter(r=>r.a.config.major===m&&r.group==='all28'),ids=[...new Set(rs.flatMap(r=>r.a.config.skillIds))];return ids.map(id=>{const yes=rs.filter(r=>r.a.config.skillIds.includes(id)),no=rs.filter(r=>!r.a.config.skillIds.includes(id));return [name[m],id,`${yes.filter(r=>r.winner===0).length}/${yes.length}`,`${no.filter(r=>r.winner===0).length}/${no.length}`,rs.reduce((n,r)=>n+(r.metrics[0].actions[id]||0),0),`${rs.reduce((n,r)=>n+(r.detail[0].available[id]||0),0)}/${rs.reduce((n,r)=>n+(r.detail[0].filtered[id]||0),0)}`];});}));body+='\n\n此表的携带／不携带结果同时改变另一技能，受组合协同和对手影响，**不是独立技能增益估计**。合法点计数是选招时可使用的次数；过滤点表示可合法使用但 AI 主动排除，不能据此认定规则禁止。低使用可能是费用／射程／机会不足，也可能是控制器偏差。\n\n';body+=table(['主修','控制器','推荐／筛选最好／筛选最弱：己方胜-败-未决'],['ignite','sustain','quick','heavy'].flatMap(m=>['script','adaptive'].map(c=>[name[m],c,['recommended','screen-best','screen-worst'].map(label=>{const a=aggregate(rows.filter(r=>r.a.config.major===m&&r.controller===c&&r.selection===label));return `${a.wins}-${a.losses}-${a.unresolved}`;}).join('／')])));body+='\n\n**逐项决定：**\n\n- 普通低耗伤害、重剑剑意消耗、护盾费用：保留，不因一个控制器的筛选排名改动。\n- 蓄势：保留 2 AP 和现有释放窗口；已按开始／兑现／打断／落空核算，暂不提高伤害。\n- 枯荣、回春与生息：保留当前值；枯荣专项与负对照已单独完成，不叠加恢复削弱。\n- 射程与移动：保留焚炎近中距；不同距离改变胜负，移动成本有实效。\n- 推荐六槽与主修奖励：本轮保留；筛选最优仅在一个固定对手／倾向／距离下成立，不能直接替换通用推荐。\n- 稀少施展的打断／追击等技能：登记为 AI 条件与适用场景复查项；没有真人或对应反制场景证据时不删除、不直接降费。\n\n本轮的交付是完成七项独立复查、固定测试控制器组合和明确采用／保留决定；没有足够一致的证据支持新增线上数值改动，因此网站规则维持当前发布版本。';}
 if(step===6)body+='\n\n有限层确认中，无补偿与护盾8都是先行动者胜7/8，通灵1反而升到8/8；多出的一胜是引燃先手对重剑。补偿改变后手储气和反应选择，可能间接帮助先手，不能只按补偿面板判断。';
 if(step===7){const tactics=decode(dir+'/tactics.json.gz');body+='\n\n另保留5个固定战术片段，主动给出可用场景（敌方正在蓄势、远距灵种、两层剑意消费），不计作完整对局，也不代表这些技能在全部场景都有收益。\n\n';body+=table(['技能','距离','AI候选包含','施展后敌方蓄势','实际气血伤害','己方剑意前→后'],tactics.map(r=>[r.id,r.distance,r.included?'是':'否',r.after.actors[1].charge?'仍在':'无',r.before.actors[1].hp-r.after.actors[1].hp,r.before.actors[0].intent+'→'+r.after.actors[0].intent]));}
 body+=`\n\n数据：[第 ${step} 项摘要](balance/sequence-${step}/summary.json)。复跑：\`node scripts/${step<5?'sequence-review':'sequence-numbers'}.mjs ${step}\`。`;section(step,{3:'代表对局与打法复查',4:'平衡测试控制器组合',5:'枯荣与资源周转',6:'先手与补偿候选',7:'配装与技能价值'}[step],body);
}
writeFileSync(path,text);
